apiVersion: v1
kind: Service
metadata:
  name: security-triage
  namespace: security-triage
  labels:
    app: security-triage
spec:
  type: ClusterIP
  selector:
    app: security-triage
  ports:
    - name: http
      port: 7300
      targetPort: http
      protocol: TCP
